### ISSUE TITLE
Artist name not displaying properly on loading screen/game play/results screen when it's too long.

### ISSUE THREAD

**Issue by freshcoool** [limyz/DTXmaniaXG#30]
![vlcsnap-2020-08-03-10h12m01s771](https://user-images.githubusercontent.com/17662561/89139602-d2a0dd80-d571-11ea-8a5f-bea2240dcf40.png)

**Comment by fisyher** [comment]
This is caused by the text rendering function automatically adding a newline if the text is too long, though I am not sure how it determines if that is the case.

**Comment by fisyher** [comment]
![Roza Updated](https://user-images.githubusercontent.com/15701545/91302780-927ff400-e7d9-11ea-81f0-27282ca9e8e1.png)
Fixed and improved. Ignore the different difficulty level. Mine is not updated
