### ISSUE TITLE
Search Songs Function

### ISSUE THREAD

**Issue by fisyher** [limyz/DTXmaniaXG#44]
As requested by Approved, as he often has trouble finding songs during live stream.

Work is currently in progress in SearchFunction Branch

**Comment by ericpignet** [comment]
Good news, good luck with this!
I was actually about to start working on a basic search function. That's good you created this ticket and said you were working on it so we don't duplicate effort.

**Comment by fisyher** [comment]
It is almost done. I will merge this back into master after adding a few more basic search functions
